# Makefile for Bingo Inc.

# *****************************************************

CXX = g++
CXXFLAGS = -Wall -g
LDFLAGS = -lwinmm

# ****************************************************

bingo:
    $(CXX) $(CXXFLAGS)  utilities/utilities.cpp \
    utilities/fileUtilities.cpp \
    utilities/vectorUtilities.cpp \
    validators/validators.cpp \
    views/views.cpp \
    views/watermark/watermarkviews.cpp \
    views/menu/menuviews.cpp \
    views/alias/aliasviews.cpp \
    views/card/cardviews.cpp \
    views/leaderboard/leaderboardviews.cpp \
    core/bingoCore.cpp \
    core/handlers.cpp \
    core/card.cpp \
    main.cpp \
    -o bingo \
    $(LDFLAGS) \
    && bingo.exe


